import Head from 'next/head'
import BarChart from './barChart'
import LineChart from './lineChart'
import DoughnutChart from './doughnut'
import styles from '@/styles/Home.module.css'
import { useEffect, useState } from 'react'

export default function Home() {
  const [data, setData] = useState([])
  const [seconds, setSeconds] = useState(0);
  const [actual, setActual] = useState()

  useEffect(() => {
    const timer = setInterval(() => {
      setSeconds((prevSeconds) => prevSeconds + 1);
    }, 5 * 1000);
    return () => clearInterval(timer);
  }, []);

  const activar = async () => {
    const response = await fetch("/api/mysql", {
      method: "GET",
      headers: {
        "Content-Type": "application/json",
      },
    });
    const data2 = await response.json();
    setData(data2)
    if (response.status !== 200) {
      throw data2.error || new Error(`Request failed with status ${response.status}`);
    }
  }

  const imprimir = () => {
    if(data.length>0){
      for (let i = 0; i<data.length; i++){
        console.log("Humeda: ", data[i].humedad)
        console.log("Fecha: ", data[i].fecha)
        console.log("Hora: ", data[i].hora)
        if(i===(data.length-1)){
          setActual(data[i].humedad)
          console.log("Valor actual: ", actual)
        }
      }
    }
  }

  useEffect(() => {
    activar()
    imprimir()
  }, [seconds])

  useEffect(() => {
    console.log("Data de bd", data)
  }, [data])

  return (
    <>
      <Head>
        <title>Dashboard</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <h2>Sensor de Húmedad</h2>
      <div className={styles.container}>
        <BarChart datos={data}></BarChart>
        <LineChart datos={data}></LineChart>
        <DoughnutChart valor={actual}></DoughnutChart>
      </div>
    </>
  )
}
