import Head from 'next/head'
import BarChart from './barChart'
import LineChart from './lineChart'
import DoughnutChart from './doughnut'
import styles from '@/styles/Home.module.css'
export default function Home() {
  const mysql = require('mysql2');
  const connection = mysql.createConnection({
    host: 'localhost',
    user: 'root',
    database: 'next',
    password: 'Bile29'
  });
  connection.query(
    'SELECT * FROM post',
    function(err, results, fields) {
      console.log("Retorno")
      console.log(results); 
      console.log(fields); 
    }
  );
  return (
    <>
      <Head>
        <title>Dashboard</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <h2>Sensor de Húmedad</h2>
      <div className={styles.container}>
        <BarChart></BarChart>
        <LineChart></LineChart>
        <DoughnutChart></DoughnutChart>
      </div>
    </>
  )
}
